import GNB from "@/components/organisms/gnb";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { Geist, Geist_Mono, Noto_Sans_KR } from "next/font/google";
import TanStackQueryProvider from "../contexts/tanstackProvider";

//  Noto Sans KR (Google Fonts)
const notoSansKR = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  subsets: ["latin"], // ["latin", "korean"] 가능
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
});

//  Geist Sans / Mono
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "최애의 포토",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${notoSansKR.variable}
          antialiased
        `}
      >
        <AuthProvider>
          <TanStackQueryProvider>
            <header>
              {/* <GNB /> */}
            </header>
            {children}
          </TanStackQueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
